directive @edfs__natsRequest(
  subject: String!
  providerId: String! = "default"
) on FIELD_DEFINITION
directive @edfs__natsPublish(
  subject: String!
  providerId: String! = "default"
) on FIELD_DEFINITION
directive @edfs__natsSubscribe(
  subjects: [String!]!
  providerId: String! = "default"
  streamConfiguration: edfs__NatsStreamConfiguration
) on FIELD_DEFINITION

input edfs__NatsStreamConfiguration {
  consumerName: String!
  streamName: String!
}

type edfs__PublishResult {
  success: Boolean!
}
