app:
  name: "account"
  version: "0.1.0"
  environment: "development"
  debug: false

database:
  driver: "postgres"
  host: "localhost"
  port: 5433
  user: "username"
  password: "password"
  database: "account"
  ssl_mode: "disable"

metrics:
  enabled: false
  port: 9093
  path: "/metrics"
  namespace: "federation"

jwt:
  secret_key: "secret"
  duration: 3600

encrypt:
  secret_key: "N1PCdw3M2B1TfJhoaY2mL736p2vCUc47"

# New servers configuration section
servers:
  http:
    enabled: true
    port: 8083
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  graphql:
    enabled: true
    playground: true