FROM golang:1.24-alpine as builder 

WORKDIR /app

RUN apk add --no-cache git ca-certificates gcc musl-dev  

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o account-service ./cmd/main/main.go


FROM alpine:3.19

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

RUN mkdir -p /app/data && chmod 777 /app/data  

COPY --from=builder /app/account-service /app/account-service

RUN addgroup -S appgroup && adduser -S appuser -G appgroup  
USER appuser  

EXPOSE 8081

# Set data directory as volume  
VOLUME ["/app/data"]  

ENTRYPOINT [ "/app/account-service" ]

CMD ["--port=8081", "--etcd-endpoints=etcd:2379", "--etcd-base-path=/services", "--service-name=account"]