version: "3.8"

services:
  # NATS Messaging Server
  nats:
    image: nats:2.11-alpine
    ports:
      - "4223:4222" # Client connections
      - "8223:8222" # HTTP monitoring
      - "6223:6222" # Routing port for clustering
    command: ["--store_dir=/data"]
    volumes:
      - nats_data:/data
    networks:
      - federation-network

  # PostgreSQL for Account Service
  db:
    image: postgres:17.5-alpine3.21
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - federation-network

  # Redis Cache
  redis:
    image: redis:8-alpine
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - federation-network

volumes:
  nats_data:
  postgres_data:
  redis_data:

networks:
  federation-network:
    driver: bridge
