app:
  name: "aggregator-service"
  version: "0.1.0"
  environment: "development"
  debug: true

server:
  port: 8081
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120

metrics:
  enabled: false
  port: 9091
  path: "/metrics"
  namespace: "federation"
  subsystem: "aggregator"

service:
  graphql:
    playground: true 