package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/gianglt2198/federation-go/services/account/generated/ent"
	"github.com/gianglt2198/federation-go/services/account/generated/graph/model"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (ent.Noder, error) {
	return r.db.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]ent.Noder, error) {
	return r.db.Noders(ctx, ids)
}

// FindAuthVerifyEntityByID implements generated.EntityResolver.
func (e *entityResolver) FindAuthVerifyEntityByID(ctx context.Context, id string) (*model.AuthVerifyEntity, error) {
	return e.authService.FindAuthByID(ctx, id)
}
