global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # - job_name: "node"
  #   static_configs:
  #     - targets: ["node_exporter:9100"]
  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8098"]
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["collector:8889"]
  # - job_name: "vector"
  #   static_configs:
  #     - targets: ["vector:9598"]