input LoginInput {
  username: String!
  password: String!
}

input RegisterInput {
  username: String!
  email: String!
  password: String!
  firstName: String
  lastName: String
  phone: String
  address: String
  avatar: String
}

input AuthVerifyInput {
  token: String!
}
