extend type Mutation {
  accountAuthRegister(input: RegisterInput!): Boolean!
  accountAuthLogin(input: LoginInput!): LoginEntity
  accountAuthLogout: Boolean!
  accountAuthVerify: AuthVerifyEntity!
}
