app:
  name: "gateway"
  version: "0.1.0"
  environment: "development"
  debug: true

metrics:
  enabled: true
  port: 9095
  path: "/metrics"
  namespace: "federation"
  subsystem: "gateway"

servers:
  http:
    enabled: true
    port: 8082
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  federation:
    enabled: true
    playground: true
    
    # Subgraph configurations
    subgraphs:
      - name: account
        url: http://localhost:8083/graphql
        timeout: 30
        retries: 3
        headers:
          Content-Type: application/json
          Authorization: "${ACCOUNT_TOKEN:-}"
      - name: catalog
        url: http://localhost:8084/graphql
        timeout: 30
        retries: 3
        headers:
          Content-Type: application/json
          Authorization: "${CATALOG_TOKEN:-}"