app:
  name: "gateway"
  version: "0.1.0"
  environment: "development"
  debug: true

tracing:
  enabled: true
  endpoint: "localhost:4317"

# NATS Configuration
nats:
  enabled: true
  name: "gateway"
  endpoint: "nats://localhost:4223"
  base_path: "federation"
  allow_reconnect: true
  max_reconnects: 500
  ping_interval: 10s

servers:
  http:
    enabled: true
    port: 8082
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  federation:
    enabled: true
    playground: true
    
    # Subgraph configurations
    subgraphs:
      - name: account.graphql
      - name: catalog.graphql