package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/gianglt2198/graphql-gateway-go/catalog/ent"
	"github.com/gianglt2198/graphql-gateway-go/catalog/graph/generated"
	"github.com/gianglt2198/graphql-gateway-go/pkg/modules/db/pnnid"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input ent.CreateProductInput) (*ent.Product, error) {
	return r.client.Product.Create().SetInput(input).Save(ctx)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id pnnid.ID, input ent.UpdateProductInput) (*ent.Product, error) {
	return r.client.Product.UpdateOneID(id).SetInput(input).Save(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
