common:
  name: catalog
  env: dev

db:
  enabled: true
  driver: postgres
  connection: "postgres://username:password@localhost:5433/postgres?sslmode=disable"

gql:
  enabled: true
  http: 
    enabled: true
    port: 7000
    path: /query
    subscription_path: /subscription
    playground_enabled: true