app:
  name: "catalog"
  version: "0.1.0"
  environment: "development"
  debug: false

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "username"
  password: "password"
  database: "catalog"
  sslmode: "disable"

metrics:
  enabled: false
  port: 9093
  path: "/metrics"
  namespace: "federation"

# New servers configuration section
servers:
  http:
    enabled: true
    port: 8083
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  graphql:
    enabled: true
    playground: true