app:
  name: "catalog"
  version: "0.1.0"
  environment: "development"
  debug: false

database:
  driver: "postgres"
  host: "localhost"
  port: 5433
  user: "username"
  password: "password"
  database: "catalog"
  ssl_mode: "disable"
  debug: true

# NATS Configuration
nats:
  enabled: true
  name: "catalog"
  endpoint: "nats://localhost:4223"
  base_path: "federation"
  allow_reconnect: true
  max_reconnects: 500
  ping_interval: 10s

tracing:
  enabled: true
  endpoint: "localhost:4317"

# New servers configuration section
servers:
  http:
    enabled: false
    port: 8084
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  graphql:
    enabled: true
    playground: false