app:
  name: "catalog"
  version: "0.1.0"
  environment: "development"
  debug: true

database:
  driver: "postgres"
  host: "localhost"
  port: 5433
  user: "username"
  password: "password"
  database: "catalog"
  ssl_mode: "disable"

metrics:
  enabled: false
  port: 9093
  path: "/metrics"
  namespace: "federation"

# New servers configuration section
servers:
  http:
    enabled: true
    port: 8084
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
  graphql:
    enabled: true
    playground: true