directive @edfs_Request(
  subject: String!
  providerId: String! = "default"
) on FIELD_DEFINITION
directive @edfs_Publish(
  subject: String!
  providerId: String! = "default"
) on FIELD_DEFINITION
directive @edfs_Subscribe(
  subjects: [String!]!
  providerId: String! = "default"
  streamConfiguration: edfs_StreamConfiguration
) on FIELD_DEFINITION

input edfs_StreamConfiguration {
  consumerInactiveThreshold: Int! = 30
  consumerName: String!
  streamName: String!
}

type edfs_PublishResult {
  success: Boolean!
}
