package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/gianglt2198/graphql-gateway-go/services/account/graph/generated"
	"github.com/gianglt2198/graphql-gateway-go/services/account/graph/model"
	"github.com/gianglt2198/graphql-gateway-go/services/account/internal/models"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	var name string
	if input.FullName != nil {
		name = *input.FullName
	}
	return models.CreateUser(input.UserName, input.Email, name), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, username *string, email *string, fullName *string) (*model.User, error) {
	var uname, mail, name string
	if username != nil {
		uname = *username
	}
	if email != nil {
		mail = *email
	}
	if fullName != nil {
		name = *fullName
	}

	user := models.UpdateUser(id, uname, mail, name)
	if user == nil {
		return nil, fmt.Errorf("user not found")
	}
	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	return models.DeleteUser(id), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return models.GetUserByID("1"), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user := models.GetUserByID(id)
	if user == nil {
		return nil, fmt.Errorf("user not found")
	}
	return user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return models.GetUsers(), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
