extend type Mutation {
  catalogCreateCategory(input: CreateCategoryInput!): Boolean!
  catalogUpdateCategory(id: ID!, input: UpdateCategoryInput!): Boolean!
  catalogDeleteCategory(id: ID!): Boolean!
}
