type UserPaginatedConnection {
  edges: [UserPaginatedEdge]
  pageInfo: PageInfo!
  totalCount: Int!
}

type UserPaginatedEdge {
  node: UserEntity
  cursor: Cursor!
}

type UserEntity implements Node @key(fields: "id") {
  id: ID!
  createdAt: Time
  createdBy: String
  updatedAt: Time
  updatedBy: String
  username: String
  email: String
  firstName: String
  lastName: String
  phone: String
}
